name: 'Run Tests'

on:
  push:
    branches: [ 'master' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Fetch Onkostar-API
        run: |
          curl --user dnpm:${{ secrets.PACKAGE_TOKEN }} \
            https://git.dnpm.dev/api/packages/Plugin-JF-Onkostar/generic/onkostar-api/2.11.1.6/onkostar-api-2.11.1.6.jar \
            --output libs/onkostar-api-2.11.1.6.jar

      - name: Fetch ATC-Codes-Plugin
        run: |
          curl \
            https://github.com/CCC-MF/onkostar-plugin-atccodes/releases/download/v0.6.0/onkostar-plugin-atccodes-0.6.0.jar \
            --output libs/onkostar-plugin-atccodes-0.6.0.jar

      - name: Execute tests
        run: mvn --batch-mode verify